name: Bug Report
description: Report a reproducible bug.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please provide enough detail to reproduce it.
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
      placeholder: Clear and concise expected behavior.
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened instead?
      placeholder: Clear and concise actual behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Include minimal model/snippet when possible.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Traceback / logs
      description: Paste relevant output.
      render: shell
  - type: input
    id: python
    attributes:
      label: Python version
      placeholder: "e.g., 3.13.12"
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      placeholder: "e.g., Ubuntu 24.04 / macOS 15 / Windows 11"
    validations:
      required: true
