name: Question
description: Ask a usage or design question.
title: "[Question]: "
labels: ["question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
      description: What do you want to understand?
      placeholder: "How can I..."
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Add model snippets or background if relevant.
